### ISSUE TITLE
Is there an official docker image?

### ISSUE THREAD

**Issue by Spritekin** [twosigma/Cook#1026]
Hi,

In my company we have been using Docker Swarm on Mesos to run about two millions of jobs per month. Unfortunately the support for Swarm on Mesos is over and we need to move on so we were evaluating options and one of them is using Cook.

So I was looking for an official twosigma mesos cook image to install but couldn't find a good one not even in the docker hub twosigma public repos.

So please is there an official image or in any case is there a way to build a docker image for this repo?

Thanks,
Guimo

**Comment by Spritekin** [comment]
I'm looking for an image that can be setup as a framework in a mesos cluster like marathon or chronos can be run as a framework, they can even be run from marathon.

**Comment by dposada** [comment]
Hey @Spritekin, sorry for the delay in responding. We have a docker image that we use for local development of Cook Scheduler. It probably isn't exactly what you're looking for, but it could certainly be modified to do whatever you need. Here is the Dockerfile:

https://github.com/twosigma/Cook/blob/master/scheduler/Dockerfile

Let me know what you think.

**Comment by Spritekin** [comment]
That's quite nice. A bit more work on the configuration and this could be an official image.

Will try it... thanks!

**Comment by dposada** [comment]
@Spritekin Sure thing, let us know how it goes.
