### ISSUE TITLE
Circuit breaker test failing

### ISSUE THREAD

**Issue by icexelloss** [twosigma/Cook#103]
Circuit breaker test is failing.

I took a quick look but doesn't feel like it's something I can fix easily.

**Comment by leifwalsh** [comment]
Which test and where?

**Comment by icexelloss** [comment]
recovery test in circuit-breaker-test. See Travis log

**Comment by icexelloss** [comment]
I have disabled the test for now #105

**Comment by wyegelwel** [comment]
Removing all clj-http-async-pool code and tests since we don't use it, see #142
