### ISSUE TITLE
Please add restart method to raw scheduler that takes one or more UUIDs and optional resource parameters

### ISSUE THREAD

**Issue by benjrossi** [twosigma/Cook#113]
A vector API like submit would be nice (i.e. takes one or more UUIDs, not just one), and perhaps also an optional number of retries.

The method would cause a new instance to be appended to the list of instances for that UUID, and would otherwise be like a submit. If the newly started job could inherit the same submit resource parameters (memory, cores) by default that would be great, and perhaps optionally the ability specify them again if that seems feasible (could be nice if the reason the last instance failed was due to those constraints).

**Comment by wyegelwel** [comment]
This has been merged, see /retry endpoint
