### ISSUE TITLE
Broken build for 2 months

### ISSUE THREAD

**Issue by dgrnbrg** [twosigma/Cook#129]
It would probably be good to fix the broken tests so that the travis build passes again.

**Comment by wyegelwel** [comment]
Was looking into it today. You may know the answer to this. Is the uri
field expected to be ordered?

**Comment by wyegelwel** [comment]
Build is fixed. However there are currently flaky tests from clj-http-async-pool which may bite us later. I have a pr #142  to remove that code because we don't currently use it. In the future we may make another code base for that code.

**Comment by dgrnbrg** [comment]
👍 🙏 🙇
