### ISSUE TITLE
Propagate the reason field for failed tasks

### ISSUE THREAD

**Issue by dgrnbrg** [twosigma/Cook#13]
The reason we show in json will be the enum value, but all lowercase, changing underscores to spaces, and dropping the leading `reason `.

Discussed with @icexelloss.

**Comment by dgrnbrg** [comment]
@icexelloss what is the name of the field in the instance's json? Should it be `"reason"`, which is only set when it failed? Or should it have a different name, or have a default value? Are there other cases we're missing?

**Comment by icexelloss** [comment]
@dgrnbrg, can you look at the initial design docs for cook error code?

https://github.com/icexelloss/Cook/blob/cook-error-code/scheduler/docs/cook-error-code

**Comment by dgrnbrg** [comment]
This looks like a good design.

**Comment by icexelloss** [comment]
Great!

I will start working on this.

**Comment by icexelloss** [comment]
#104
