### ISSUE TITLE
Cook Spark Scheduler: Provide ability to set priority for spark exectutors

### ISSUE THREAD

**Issue by tnn1t1s** [twosigma/Cook#134]
We' d like the ability to pass the priority of the spark jobs to the cook scheduler.  This would let users prefer Spark jobs over other workloads in Cook

**Comment by tnn1t1s** [comment]
as per @leif, The spark config property spark.cook.priority is passed through to cook. This work could be as simple as documenting this and running tests to validate priority works as expected in the case of a mix of spark and non-spark by a single user

**Comment by wyegelwel** [comment]
I believe this is done and we have moved the spark part of the project to github.com/twosigma/spark
