### ISSUE TITLE
Remove the metatransaction code in favor of simpler is-committed attribute on jobs

### ISSUE THREAD

**Issue by wyegelwel** [twosigma/Cook#143]
This is-committed attribute could go to a commit entity that has a state which is either committed or uncommitted. This will give the same semantics as metatransaction now with a less serious performance hit and a simpler deploy story.

**Comment by DaoWen** [comment]
@wyegelwel - is this describing the commit latch in the current code?

**Comment by wyegelwel** [comment]
yes.
