### ISSUE TITLE
Simplify job state logic

### ISSUE THREAD

**Issue by wyegelwel** [twosigma/Cook#148]
Currently there is a valid state where a job is "waiting" and an instance is status "unknown". This complicates a lot of logic and is the source of bugs. For example, jobs in state waiting are in the pending state, but instances in running and unknown are in treated as running, therefore the waiting/unknown jobs are double counted.

First determine if this state combination is necessary and if it is not, remove it.

@dgrnbrg, do you remember the reason the waiting,unknown pair state exists? Li and I could not. There are some failure scenarios where treating the job as waiting before it calls home is semantically pleasant but I'm not sure it is worth the added complexity.

**Comment by dgrnbrg** [comment]
If we have accepted an offer but not recieved an ack from Mesos, then the
instance is unknown (the accepted offer could be dropped; it's not a
guaranteed message), and the job is pending, since we don't know if it's
running yet.

**Comment by wyegelwel** [comment]
What I'm wondering is what that buys us. Or asked another way, if I was to change it such that when we accept an offer we mark the job as running, would we be losing a necessary state? I *think* the answer is no, however, I thought you might remember otherwise.

**Comment by dgrnbrg** [comment]
launchTasks isn't guaranteed delivery. Instances need an intermediate state
so that we don't match them with multiple offers, and so that we can decide
when the launch failed (timed out).

**Comment by wyegelwel** [comment]
I agree, instances need an intermediate state (unknown) until they are confirmed scheduled. However, it is not necessary that the job must be in state "waiting" (as opposed to being set to running). Do you agree?

My goal here is to reduce ambiguous states.
