### ISSUE TITLE
Provide executor for raw scheduler API instead of using default command line executor

### ISSUE THREAD

**Issue by WenboZhao** [twosigma/Cook#173]
A few importance features could be implemented by using the customized executor
(1) progress report
(2) consolidated and nice formatted log
(3) reliable outputURL for job
(4) expose outputURL to Spark executor and thus the Spark UI in the driver for easy debugging.

**Comment by wyegelwel** [comment]
I agree, we should move to this. 

What do you mean by (2)?

**Comment by WenboZhao** [comment]
For (2), I meant merge stderr, stdout and possible other logs into one single file for ease of browsing and adding timestamp etc.

**Comment by wyegelwel** [comment]
Another feature could be to capture and send back the exit code of the job. The mesos status update currently doesn't provide this.

**Comment by sgopalan** [comment]
Many users have also requested SFv1-like email notification options for failed, completed jobs.

This is very helpful if you have a long-running job and only want to know if it has broken or it has completed.

**Comment by sgopalan** [comment]
Could this also incorporate the functionality of the task proxy (http://dft-task-proxy.app.twosigma.com:28880) which flattens the raw output into human-readable form?

**Comment by shamsimam** [comment]
The current plan with the custom executor:
1. Provide progress update messages to the scheduler
2. Send the exit code of the job to the scheduler
3. Send the sandbox location of the job to the scheduler

**Comment by shamsimam** [comment]
The Cook Executor is being successfully used as the default executor.
