### ISSUE TITLE
Reason code for failed jobs

### ISSUE THREAD

**Issue by m4ce** [twosigma/Cook#181]
I see there was work to propagate the reason code for failed jobs. However, it looks like it's not showing up for some reasons. My jobs have failed due to memory limitation. However, when querying the status of the job, I do not see any reason field.

```
Sep 15 15:03:14 foo kernel: Killed process 27918 (python) total-vm:1357356kB, anon-rss:1023804kB, file-rss:0kB
Sep 15 15:03:14 foo systemd: Stopped docker container 797b6bffc3760a5cf766965de3248d2eff58479c0ccd8d5315b39dbe4ea5c13f.
Sep 15 15:03:14 foo systemd: Stopping docker container 797b6bffc3760a5cf766965de3248d2eff58479c0ccd8d5315b39dbe4ea5c13f.
Sep 15 15:03:14 foo journal: time="2016-09-15T15:03:14.752321974Z" level=info msg="{Action=wait, ID=797b6bffc3760a5cf766965de3248d2eff58479c0ccd8d5315b39dbe4ea5c13f, LoginUID=4
294967295, PID=27881}"
Sep 15 15:03:14 foo kernel: XFS (dm-1): Unmounting Filesystem
Sep 15 15:03:14 foo mesos-slave[14656]: I0915 15:03:14.868490 14692 slave.cpp:3211] Handling status update TASK_FAILED (UUID: edc3f4d2-fdb0-4163-adcf-ac58730d11ff) for task 92af32c4-d78e-4960-a78b-2a03070bc047 of framework 2566d37b-3913-4069-baa0-a4a398bddf1c-0000 from executor(1)@10.0.0.1:43590
Sep 15 15:03:14 foo mesos-slave[14656]: I0915 15:03:14.920524 14689 status_update_manager.cpp:320] Received status update TASK_FAILED (UUID: edc3f4d2-fdb0-4163-adcf-ac58730d11ff) for task 92af32c4-d78e-4960-a78b-2a03070bc047 of framework 2566d37b-3913-4069-baa0-a4a398bddf1c-0000
..
```

Query the status:
```
[root@hkgcpu10 mesos]# curl -u user: -X GET http://cook:12321/rawscheduler?job=62469824-7b55-11e6-a363-000c295e64ae
[{"labels":{},"mem":1000.0,"max_retries":1,"max_runtime":86400000,"name":"cookjob","command":"python \/test.py","env":{},"framework_id":null,"ports":0,"instances":[{"start_time":1473951736936,"executor_id":"92af32c4-d78e-4960-a78b-2a03070bc047","hostname":"foo","slave_id":"5cbb4cd9-cefd-4daa-a421-376d89328ab6-S6","preempted":false,"end_time":1473951794921,"backfilled":false,"ports":null,"status":"failed","task_id":"92af32c4-d78e-4960-a78b-2a03070bc047"}],"priority":50,"status":"completed","uuid":"62469824-7b55-11e6-a363-000c295e64ae","uris":null,"cpus":1.5}]
```

You can see that the task id is the same: 92af32c4-d78e-4960-a78b-2a03070bc047

**Comment by wyegelwel** [comment]
Are these logs from the mesos slave log or the executor log?

You can check the cook log to see if it got the memory limit exceeded reason from mesos and didn't propogate it correctly or if mesos didn't recognize it as memory limit exceeded.

**Comment by m4ce** [comment]
Hi @wyegelwel,

unfortunately, I set the cook log level to WARNING.. so I guess I won't be able to see those messages if they are reported using loglevel INFO. I checked the cook.log and didn't see anything.

Thanks,
Matteo

**Comment by m4ce** [comment]
By the way, those logs are from the slave. The executor logs don't contain much info.

**Comment by wyegelwel** [comment]
Hmm, unfortunately we only print the status from mesos with log level info.

What log level do you have for the mesos masters? You might be able to find the status message there.

Alternatively, you could try setting cook log level to info for a little while and re-run the job. I'm wondering if your python process got killed by Dockers oom killer and so mesos doesn't treat it as a memory limit exceeded error.

For what it is worth we have previous observed memory limit exceeded reasons when querying cook.

**Comment by wyegelwel** [comment]
Also sorry if that was a bit unclear I'm typing on my phone.

**Comment by m4ce** [comment]
I had a look at the mesos master, and don't see much there beside the "Status update TASK_FAILED" message for the task.

I'm running the default log level there, which is INFO.

I think you are right about the Docker OOM killer. I guess Mesos doesn't catch.. only option would be to use mesos containers.

**Comment by m4ce** [comment]
Verified this using Mesos native containers (instead of Docker) and reason is propagated indeed when container gets killed due to OOM.
