### ISSUE TITLE
Provide an endpoint to tell why a job isn't being scheduled

### ISSUE THREAD

**Issue by wyegelwel** [twosigma/Cook#201]
There are a lot of reasons a job isn't being scheduled and users often don't know why. Some potential reasons are:
1. They are at their quota
2. The job is already running
3. The job is backing off
4. The job requires a lot of resources and no machines are available

**Comment by wyegelwel** [comment]
Bonus points if there is a time series of these reasons.

**Comment by dposada** [comment]
Was this resolved by PR #212 ?
