### ISSUE TITLE
Retrieve Job UUID from Task ID

### ISSUE THREAD

**Issue by m4ce** [twosigma/Cook#205]
Hi,

is there any way to retrieve a job uuid from a task-id?

When querying the /running and /queue endpoints, no job uuid is returned.

```
curl -X GET -u mace: http://127.0.0.1:12321/running
[{"instance/task-id":"4c27d82e-e976-4588-a61e-a2ac2fb36fcb","instance/progress":0,"instance/backfilled?":false,"instance/hostname":"node3","instance/executor-id":"4c27d82e-e976-4588-a61e-a2ac2fb36fcb","instance/slave-id":"d8975e23-6600-4200-bde5-9b371beec830-S57","instance/status":"instance.status/running","instance/start-time":"2016-11-01T00:26:20Z","instance/preempted?":false}]%
```

Ths is particurarly useful when having to kill stale jobs.

Thanks,
Matteo

**Comment by wyegelwel** [comment]
At the moment no, but there is a PR that adds the ability (and a lot more, that is why it is sitting).

Here is the commit if you want to try to cherry-pick it: 

https://github.com/twosigma/Cook/pull/185/commits/0db331906445c8da9348c4f2cd434a14e017fa66

**Comment by m4ce** [comment]
@wyegelwel, thanks for pointing me out to that tcommit :)

**Comment by wyegelwel** [comment]
It is now in the mainline of Cook.

If you haven't seen, we are adding swagger definitions for the endpoints.
