### ISSUE TITLE
Cannot start docker containers anymore

### ISSUE THREAD

**Issue by m4ce** [twosigma/Cook#206]
Hi,

I tried to test the latest master and it seems like that docker support is broken. The job is submitted successfully but then the container starts as a mesos container rather than a docker one.

Could it be related to the move to Mesomatic? When running until commit id 169228602111d1065ab99933687a6c789d3d458e, everything works as expected.

I will try to troubleshoot more and provide you with my findings.

**Comment by wyegelwel** [comment]
Yea that is the *other* thing fixed my big pr that is pending. 

I would recommend staying at the hash you are few more days until we can get it merged. 

Sorry about that, we will be adding docker support to the integration tests so this won't happen again.

**Comment by m4ce** [comment]
@wyegelwel, thanks for your quick reply and for the great work.
