### ISSUE TITLE
Add field in job to give job status that includes "failed"

### ISSUE THREAD

**Issue by wyegelwel** [twosigma/Cook#223]
Currently the api at the job level has statuses "waiting", "running" and "completed". To determine if a job succeeded or failed, it requires checking if all the instances of the job are failed or if at least one succeeded. This is fairly tedious and is required for any client that works with Cook. Adding a new field that does this on the server side would be extremely helpful.

**Comment by wyegelwel** [comment]
#232

**Comment by dposada** [comment]
Was this resolved by PR #232?

**Comment by DaoWen** [comment]
Closing this. It seems to have been resolved in #232.
