### ISSUE TITLE
WIP: Integration test plan 

### ISSUE THREAD

**Issue by wyegelwel** [twosigma/Cook#265]
Currently cook relies on the (system simulator)[https://github.com/twosigma/Cook/tree/master/simulator] for integration testing. However, this is problematic because it doesn't cover all the endpoints and the tests are not minimal meaning that it is possible to roll out backwards in-compatible changes without the tests catching it. Further, the simulator does far more than provide integration style testing which often makes it too heavy weight for the integration style testing operators and developers are interested in.

This document outlines what we hope to test, what won't be tested and notes areas that will be difficult to test and how to address it.

# Tests

## Submission (POST /rawscheduler)

1. ~~Minimal submission and ensure job completes (see https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/mesos/api.clj#L191 for current definition of minimal. Note, we broke backwards compatible by requiring "name", "priority" and "max_runtime")~~
2. ~~Minimal submission of failing job and ensure it fails~~
3. ~~Submission with a short max runtime and ensure job fails for exceeding max run time~~
4. Check that name regex is fully used (so that we can't make it more restrictive without failing this test) ( https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/mesos/api.clj#L174)
5. Submit a job with max_retries >1 and ensure multiple instances are run
6. Submit a job that uses more memory than requested and ensure the job fails because of container memory exceeded. Check the reason code is what is expected (https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/mesos/schema.clj#L857) 

## Group submission (POST /rawscheduler)

1. ~~Submit with an implicit group (jobs refer to a group uuid that doesn't exist and isn't in submission)~~
2. ~~Submit with an explicit group with all defaults~~
3. ~~Submit with an explicit group with straggler handling, ensure the expect job fails because it ran too long (submit 2 jobs, 1 that sleeps 1 second, one that sleeps 100000 seconds)~~
4. 

## Job querying (GET /rawscheduler?job=)

1. Ensure expected keys are there

## Job cancelling (DELETE /rawscheduler?job=)

1. ~~Submit a job, cancel it and ensure it is marked as completed~~
2. Submit multiple jobs and cancel all of them in a single request

## Job retrying (PUT, POST /retry?job=)

1. ~~Submit a job, cancel it and then retry it and ensure it runs again~~
2. Submit multiple jobs, cancel them and retry all the jobs in a single request
3. Submit a job and retry it using increment retries (as opposed to setting retries)

## Instance querying (GET /rawscheduler?instance=)

1. ~~Query the instance and ensure the expected keys are there~~

## Instance canceling (DELETE /rawscheduler?instance=)

1. ~~Kill an instance and ensure another instance is started~~

## unset quota (DELETE /quota)

# Not tested

1. Preemption / rebalancer

**Comment by DaoWen** [comment]
We currently have a pretty extensive extensive integration test suite. Closing.
