### ISSUE TITLE
Possible bug: create-jobs! assigns a new commit latch to each job

### ISSUE THREAD

**Issue by shamsimam** [twosigma/Cook#286]
In `api.clj` we have:

```
(s/defn make-job-txn
  [job :- Job]
  ...
        commit-latch-id (d/tempid :db.part/user)
        commit-latch {:db/id commit-latch-id
                      :commit-latch/uuid (UUID/randomUUID)
                      :commit-latch/committed? true}
  ...)
  
(defn create-jobs!
  [conn {:keys [::groups ::jobs] :as ctx}]
  ...
          job-txns (mapcat #(make-job-txn %) jobs)
  ...
      @(d/transact
        conn
        (concat job-txns group-txns))
  ...)  
```

This creates a new commit latch for every job submitted in the call to `create-jobs!` as `commit-latch/uuid (UUID/randomUUID)` generates a new UUID everytime. Is this intentional?

**Comment by shamsimam** [comment]
@wyegelwel  @mforsyth what do you guys think?

**Comment by mforsyth** [comment]
@shamsimam The documentation about commit latches says 

"A commit latch is used to determine if a job should be considered
             for scheduling. Many jobs can share the same commit latch if they
             should be considered schedulable at the same time. However, it is
             recommended not to consider jobs that share a commit latch to hold
             any semantic meaning other than they will be considered schedulable
             at the same time. A primitive of job group will be added to add
             more semantic power in the future."

This suggests that the jobs could share a commit latch to save some datoms, but that it's probably not very important that they do.   Beyond that I will defer to @wyegelwel to answer this :)

**Comment by wyegelwel** [comment]
@shamsimam, this is "correct". The first step for introducing the commit latch was to have every job be committed when it is submitted. Then we can have a subsequent feature where we expose the commit logic to users.

Note, we have a tool internally that is already leveraging the commit logic by touching the db directly.

**Comment by shamsimam** [comment]
Okay, closing the issue.
