### ISSUE TITLE
Allow DNS and Hostname to be configurable

### ISSUE THREAD

**Issue by dgrnbrg** [twosigma/Cook#31]
Either this should be configurable, or they're no longer in use. Either way, we should figure them out!

**Comment by dgrnbrg** [comment]
@icexelloss @mayurjpatel Do we need this still for the internal cluster kerberos deployment? If not, what's the solution for service tickets when the kerberos server name is actually a CNAME?

**Comment by mayurjpatel** [comment]
I dont think this is needed. When I set up cook scheduler, I only had to make sure HTTP principal in KRB5_KTNAME matched hostname in the curl command.

**Comment by dgrnbrg** [comment]
Before I close this issue, I just want to confirm that you saw a cname
domain work?

**Comment by mayurjpatel** [comment]
What I have is:

* cook running on hostA.domain.com with ip of 192.168.1.2
* DNS A record exists for cook.domain.com -> 192.168.1.2 
* Successfully schedule a job by going to http://cook.domain.com:12321/rawscheduler
* Going to http://hostA.domain.com:12321/rawscheduler throws a GSS auth error.

I don't have a CNAME record.
