### ISSUE TITLE
Add support for host constraints

### ISSUE THREAD

**Issue by dgrnbrg** [twosigma/Cook#42]
This should be for things like "only on hosts w/ a specific attribute". This will enable things like GPU or machine class aware scheduling.

This will need to be added to the client-facing API, as well as to the scheduler & db.

**Comment by shamsmahmood** [comment]
Below is a patch for accepting host-constraints in the job requests to cook.
---------------------------

commit b9cded6b79b5180c044ebc37f028d828afb5355a
Author: Shams Imam <shams.mahmood@gmail.com>
Date:   Fri Oct 9 16:35:02 2015 +0100

    -- accept host constraints in the cook json api

diff --git a/scheduler/docs/scheduler-rest-api.asc b/scheduler/docs/scheduler-rest-api.asc
index 93e4143..3a2f340 100644
--- a/scheduler/docs/scheduler-rest-api.asc
+++ b/scheduler/docs/scheduler-rest-api.asc
@@ -75,6 +75,7 @@ The request body is list of job maps with each entry containing a map of the fol
 |`mem` | double | MB of requested memory.
 |`uris` | list of URI objects | A list of URIs that will be fetched into the container before launch.
 |`env` | JSON map | A map of environment variables to be provided to the job.
+|`host_constraints` | JSON map | A map of host constraints to be provided to the job.
 |====
 
 .URI JSON Schema (see http://mesos.apache.org/documentation/latest/fetcher/[the Mesos docs] for details)
@@ -100,6 +101,7 @@ The request body is list of job maps with each entry containing a map of the fol
          "cpus" : 1.5,
          "uuid" : "26719da8-394f-44f9-9e6d-8a17500f5109",
          "env" : { "MY_VAR" : "foo" },
+         "host_constraints" : { "ATTRIBUTE_1" : "MatchString" },
          "uris" : [
              {
                  "value": "http://example.com/my-executor.tar.gz",
diff --git a/scheduler/src/cook/mesos/api.clj b/scheduler/src/cook/mesos/api.clj
index a3a2e27..a368a93 100644
--- a/scheduler/src/cook/mesos/api.clj
+++ b/scheduler/src/cook/mesos/api.clj
@@ -57,6 +57,7 @@
    (s/optional-key :uris) [Uri]
    (s/optional-key :ports) [(s/pred zero? 'zero)] ;;TODO add to docs the limited uri/port support
    (s/optional-key :env) {NonEmptyString s/Str}
+   (s/optional-key :host-constraints) {NonEmptyString NonEmptyString}
    :cpus PosDouble
    :mem PosDouble
    ;; Make sure the user name is valid. It must begin with a lower case character, end with
@@ -65,7 +66,7 @@
 
 (sm/defn submit-jobs
   [conn jobs :- [Job]]
-  (doseq [{:keys [uuid command max-retries max-runtime priority cpus mem user name ports uris env]} jobs
+  (doseq [{:keys [uuid command max-retries max-runtime priority cpus mem user name ports uris env host_constraints]} jobs
           :let [id (d/tempid :db.part/user)
                 ports (mapv (fn [port]
                               ;;TODO this schema might not work b/c all ports are zero
@@ -95,6 +96,13 @@
                                   :environment/name k
                                   :environment/value v}]))
                             env)
+                host-constraints (mapcat (fn [[k v]]
+                              (let [host-constraint-id (d/tempid :db.part/user)]
+                                [[:db/add id :job/host-constraints host-constraint-id]
+                                 {:db/id host-constraint-id
+                                  :host-constraint/attribute k
+                                  :host-constraint/pattern v}]))
+                                         host_constraints)
                 ;; These are optionally set datoms w/ default values
                 maybe-datoms (concat
                                (when (and name (not= name "cookjob"))
@@ -118,6 +126,7 @@
     @(d/transact conn (-> ports
                           (into uris)
                           (into env)
+                          (into host-constraints)
                           (into maybe-datoms)
                           (conj txn))))
   "ok")
@@ -135,7 +144,7 @@
 (defn validate-and-munge-job
   "Takes the user and the parsed json from the job and returns proper
    Job objects, or else throws an exception"
-  [db user task-constraints {:strs [cpus mem uuid command priority max_retries max_runtime name uris ports env] :as job}]
+  [db user task-constraints {:strs [cpus mem uuid command priority max_retries max_runtime name uris ports env host_constraints] :as job}]
   (let [munged (merge
                  {:user user
                   :uuid (UUID/fromString uuid)
@@ -156,7 +165,10 @@
                                uris)})
                  (when env
                    ;; Remains strings
-                   {:env env}))]
+                   {:env env})
+                 (when host_constraints
+                   ;; Remains strings
+                   {:host-constraints host_constraints}))]
     (s/validate Job munged)
     (when (> cpus (:cpus task-constraints))
       (throw (ex-info (str "Requested " cpus " cpus, but only allowed to use " (:cpus task-constraints))
@@ -239,6 +251,7 @@
        :status (name (:job/state job))
        :uris (:uris resources)
        :env (util/job-ent->env job)
+       :host-constraints (util/job-ent->host-constraints job)
        ;;TODO include ports
        :instances
        (map (fn [instance]
diff --git a/scheduler/src/cook/mesos/schema.clj b/scheduler/src/cook/mesos/schema.clj
index ec8b79f..e15487e 100644
--- a/scheduler/src/cook/mesos/schema.clj
+++ b/scheduler/src/cook/mesos/schema.clj
@@ -56,6 +56,11 @@
      :db/cardinality :db.cardinality/many
      :db.install/_attribute :db.part/db}
     {:db/id (d/tempid :db.part/db)
+    :db/ident :job/host-constraints
+    :db/valueType :db.type/ref
+    :db/cardinality :db.cardinality/many
+    :db.install/_attribute :db.part/db}
+    {:db/id (d/tempid :db.part/db)
      :db/ident :job/state
      :db/valueType :db.type/ref
      :db/cardinality :db.cardinality/one
@@ -103,16 +108,27 @@
     :db/cardinality :db.cardinality/many
     :db.install/_attribute :db.part/db}
    ;; Environment Variable attributes
-    {:db/id (d/tempid :db.part/db)
-     :db/ident :environment/name
-     :db/valueType :db.type/string
-     :db/cardinality :db.cardinality/one
-     :db.install/_attribute :db.part/db}
-    {:db/id (d/tempid :db.part/db)
-     :db/ident :environment/value
-     :db/valueType :db.type/string
-     :db/cardinality :db.cardinality/one
-     :db.install/_attribute :db.part/db}
+   {:db/id (d/tempid :db.part/db)
+    :db/ident :environment/name
+    :db/valueType :db.type/string
+    :db/cardinality :db.cardinality/one
+    :db.install/_attribute :db.part/db}
+   {:db/id (d/tempid :db.part/db)
+    :db/ident :environment/value
+    :db/valueType :db.type/string
+    :db/cardinality :db.cardinality/one
+    :db.install/_attribute :db.part/db}
+   ;; Host Constraint attributes
+   {:db/id (d/tempid :db.part/db)
+    :db/ident :host-constraint/attribute
+    :db/valueType :db.type/string
+    :db/cardinality :db.cardinality/one
+    :db.install/_attribute :db.part/db}
+   {:db/id (d/tempid :db.part/db)
+    :db/ident :host-constraint/pattern
+    :db/valueType :db.type/string
+    :db/cardinality :db.cardinality/one
+    :db.install/_attribute :db.part/db}
     ;; Resource attributes
     {:db/id (d/tempid :db.part/db)
      :db/ident :resource/type
diff --git a/scheduler/src/cook/mesos/util.clj b/scheduler/src/cook/mesos/util.clj
index cfffada..f630db4 100644
--- a/scheduler/src/cook/mesos/util.clj
+++ b/scheduler/src/cook/mesos/util.clj
@@ -38,6 +38,16 @@
           {}
           (:job/environment job-ent)))
 
+(defn job-ent->host-constraints
+  "Take a job entity and return the host constraints map"
+  [job-ent]
+  (reduce (fn [m host-constraint]
+            (assoc m
+              (:host-constraint/attribute host-constraint)
+              (:host-constraint/pattern host-constraint)))
+          {}
+          (:job/host-constraints job-ent)))
+
 (defn job-ent->resources
   "Take a job entity and return a resource map. NOTE: the keys must be same as mesos resource keys"
   [job-ent]
diff --git a/scheduler/test/cook/test/mesos/api.clj b/scheduler/test/cook/test/mesos/api.clj
index 3e48eae..adbc73c 100644
--- a/scheduler/test/cook/test/mesos/api.clj
+++ b/scheduler/test/cook/test/mesos/api.clj
@@ -108,14 +108,17 @@
 
 (deftest job-validator
   (let [conn (restore-fresh-database! "datomic:mem://mesos-api-test")
-        job (fn [cpus mem] {"uuid" (str (java.util.UUID/randomUUID))
-                            "command" "hello world"
-                            "name" "my-cool-job"
-                            "priority" 66
-                            "max_retries" 100
-                            "max_runtime" 1000000
-                            "cpus" cpus
-                            "mem" mem})
+        job-with-constraints (fn [cpus mem host-constraints]
+                               (merge {"uuid" (str (java.util.UUID/randomUUID))
+                                       "command" "hello world"
+                                       "name" "my-cool-job"
+                                       "priority" 66
+                                       "max_retries" 100
+                                       "max_runtime" 1000000
+                                       "cpus" cpus
+                                       "mem" mem}
+                                      (when host-constraints {"host_constraints" host-constraints})))
+        job (fn [cpus mem] (job-with-constraints cpus mem false))
         h (handler conn "my-framework-id" {:cpus 3.0 :memory-gb 2})]
     (testing "Within limits"
       (is (<= 200
@@ -152,4 +155,40 @@
                            :headers {"Content-Type" "application/json"}
                            :authorization/user "dgrnbrg"
                            :params {"jobs" [(job 1 2050)]}}))
+              499)))
+    (testing "Valid Host Constraints"
+      (is (<= 200
+              (:status (h {:request-method :post
+                           :scheme :http
+                           :uri "/rawscheduler"
+                           :headers {"Content-Type" "application/json"}
+                           :authorization/user "dgrnbrg"
+                           :params {"jobs" [(job-with-constraints 3 2048 {"attr1" "val1" "attr2" "val2"})]}}))
+              299)))
+    (testing "Invalid Host Constraints 1"
+      (is (<= 400
+              (:status (h {:request-method :post
+                           :scheme :http
+                           :uri "/rawscheduler"
+                           :headers {"Content-Type" "application/json"}
+                           :authorization/user "dgrnbrg"
+                           :params {"jobs" [(job-with-constraints 3 2048 {"numeric_attr" 1 "attr2" "val2"})]}}))
+              499)))
+    (testing "Invalid Host Constraints 2"
+      (is (<= 400
+              (:status (h {:request-method :post
+                           :scheme :http
+                           :uri "/rawscheduler"
+                           :headers {"Content-Type" "application/json"}
+                           :authorization/user "dgrnbrg"
+                           :params {"jobs" [(job-with-constraints 3 2048 {"empty_attr" ""})]}}))
+              499)))
+    (testing "Invalid Host Constraints 3"
+      (is (<= 400
+              (:status (h {:request-method :post
+                           :scheme :http
+                           :uri "/rawscheduler"
+                           :headers {"Content-Type" "application/json"}
+                           :authorization/user "dgrnbrg"
+                           :params {"jobs" [(job-with-constraints 3 2048 {"nil_attr" nil "attr2" "val2"})]}}))
               499)))))

**Comment by dgrnbrg** [comment]
@shamsmahmood Can you comment on what you did at the Mesoscon Europe hackathon on this?

**Comment by shamsmahmood** [comment]
I added support in the Cook json api to accept host constraints as key value pairs. The database schema has also been updated so that these constraints are stored in the database. The unit tests in api.clj should also help explain what has been done (https://github.com/shamsmahmood/Cook).

**Comment by dgrnbrg** [comment]
#69 has the API side of this implemented. Once #84 is merged, it should be easy to complete the integration, as #84 includes an API for adding constraints.

**Comment by DaoWen** [comment]
@shamsimam - I think this is done now, right? Please close this if you agree.

**Comment by shamsimam** [comment]
Was implemented in https://github.com/twosigma/Cook/pull/284
