### ISSUE TITLE
Docker containers not working?

### ISSUE THREAD

**Issue by m4ce** [twosigma/Cook#451]
Hi,

I am testing Cook 1.5.6 and I cannot quite seem to get any docker containers working :/

```
2017-09-14 22:02:22,432 INFO  cook.mesos.api [qtp1660338734-42] - Submitting jobs through raw api: [{:disable-mea-culpa-retries false, :mem 8192.0, :name hello_world, :command /run.sh --date 20170828, :max-r
untime 10800000, :ports 0, :priority 100, :container {:type DOCKER, :docker {:image hello_world:1.0.0, :network HOST, :force-pull-image true, :parameters [{:key user, :value 2001:2001} {:key oom-kill-disable, :value true}]}, :
volumes [{:container-path /data, :host-path /data, :mode ro}]}, :max-retries 1, :uuid #uuid "626734d2-9998-11e7-aa8e-0242ac110002", :user foo, :cpus 4.0}]
....
2017-09-14 22:20:58,652 INFO  cook.mesos.scheduler [clojure-agent-send-pool-4] - Mesos status is: #mesomatic.types.TaskStatus{:task-id #mesomatic.types.TaskID{:value 369adb5c-d538-4b42-b19f-c38491bf6f4b}, :state :task-running, :message , :source :source-executor, :reason :reason-command-executor-failed, :data #object[com.google.protobuf.LiteralByteString 0x72ed8391 <ByteString@72ed8391 size=0>], :slave-id #mesomatic.types.SlaveID{:value f9d0d740-b189-4055-a93a-fc8f1bf188b9-S4}, :executor-id #mesomatic.types.ExecutorID{:value 369adb5c-d538-4b42-b19f-c38491bf6f4b}, :timestamp 1.505427658646145E9, :uuid #object[com.google.protobuf.LiteralByteString 0x5fdffc6c <ByteString@5fdffc6c size=16>], :healthy false}
```

When the task runs on the mesos slave node, it fails as the wrong executor seem to be chosen.

stderr:

```
I0914 22:02:24.409549 24151 exec.cpp:162] Version: 1.1.0
I0914 22:02:24.411566 24151 exec.cpp:237] Executor registered on agent 9c628621-dcee-4b65-80fd-5be997018fc6-S8
sh: /run.sh: No such file or directory
```

stdout:

```
Received SUBSCRIBED event
Subscribed executor on cpu11
Received LAUNCH event
Starting task 746bf612-a264-475f-a381-cb35370aea7b
/usr/libexec/mesos/mesos-containerizer launch --command="{"environment":{},"shell":true,"user":"foo","value":"\/run.sh --date 20170828"}" --help="false" --unshare_namespace_mnt="false"
Forked command at 24154
Command exited with status 127 (pid: 24154
```

It used to work with previous versions of Cook. Nothing changed besides the scheduler...

**Comment by m4ce** [comment]
I had a look at the state.json and it looks like the task doesn't actually get submitted to Mesos as a docker container. I wonder if the problem is in mesomatic?

**Comment by wyegelwel** [comment]
Hey Matteo! Sorry you hit into this bug. The team is at mesoscon this week
so we probably won't get a chance to dig into this until next week.

I saw you just put a pr to mesomatic to add force pull support. Have you
been able to test that that fixes the problem?

We currently don't have integration tests for docker because we run mesos
in a docker container for those tests and had problems with the nested
containers. We also don't use force pull internally so didn't notice it was
missing. We will look at adding docker tests so we can prevent a regression
in the future.

**Comment by m4ce** [comment]
Hi @wyegelwel,

unfortunately, that doesn't fix my problem :/ I am looking at mesomatic as I am fairly sure that the issue is there. However, clojure is not my language so it's taking me quite some time to investigate.

It seems that the mesomatic doesn't fill the the task with the ContainerInfo configuration..

Do you know how I can dump what Mesomatic sends to Mesos?

**Comment by wyegelwel** [comment]
I can't seem to get line numbers on my phone but if you go into
scheduler/src/cook/mesos/scheduler.clj and go to the function
launch-matched-tasks there is a debug line to print that starts with
"matched task-infos". You can either set the log level to debug for the
scheduler namespace in the config or change that debug line to info or
higher. That should print what you are interested in.

**Comment by shamsimam** [comment]
Hi Matteo,

> It used to work with previous versions of Cook. Nothing changed besides the scheduler...

Can you let us know which is the last known version of the cook scheduler it was working with? It'll help isolate the issue. Thanks.

Shams.

**Comment by m4ce** [comment]
@shamsimam, the last time it was working it was at this commit -> https://github.com/twosigma/Cook/tree/169228602111d1065ab99933687a6c789d3d458e.

I might've traced the issue. In mesos/task.clj, under `defn job->task-metadata`, `container (util/job-ent->container db job-ent)` seems to always return nil.

Because it returns nil, executor-key is set to `:command-executor`, rather than `:container-command-executor` or `:container-executor`.

**Comment by shamsimam** [comment]
Thanks for debugging, we'll get it fixed soon :)

**Comment by DaoWen** [comment]
FYI, I created an integration test that reproduces the buggy behavior:

https://github.com/DaoWen/Cook/commit/eb07ddb3074c868b4864d4f4c49095e10a7dd925.patch

**Comment by DaoWen** [comment]
It looks like this broke in 8db0cc641e5b1572645a89ee684c63db9ecfdfe7.

**Comment by m4ce** [comment]
Thanks for looking into it too. I will wait for you guys to fix it then.

**Comment by DaoWen** [comment]
@m4ce - I think the issue is fixed! Please let us know if you're still having issues after pulling #453.

**Comment by wyegelwel** [comment]
@m4ce, It is worth mentioning that the cook executor should be considered
experimental at the moment and we aren't using it internally yet. If you
remove the executor block from the config it will default back to the
standard command executor.

**Comment by m4ce** [comment]
Thanks a lot. Any chance this [PR](https://github.com/pyr/mesomatic/pull/40) can be merged? Mesomatic doesn't support the force-pull-image option unfortunately.
