### ISSUE TITLE
Change the way we load Mesos in travis to enable moving to travis container infra

### ISSUE THREAD

**Issue by dgrnbrg** [twosigma/Cook#46]
This will require submitting a request to here: https://github.com/travis-ci/apt-source-whitelist

Or we can download and install/unpack/build (or grab binaries) Mesos ourselves

But this also has the problem/downside that to get them added to the whitelist, they seem to need source packages. And to use the cache (necessary for building the package), we'd need to be a paying Travis customer.

This is trickier than I initially thought.

**Comment by dgrnbrg** [comment]
I don't think this matters much. Now that @leifwalsh made the builds prettier, I'll wait until I hear about someone else figuring this out.

**Comment by leifwalsh** [comment]
I think this is orthogonal to what I did.  Might still be worth getting over to containers soonish.

**Comment by dgrnbrg** [comment]
What do you think about my evalin the issue? Seems impossibly hard, right?
Or we could try to get libmesos hosted?

**Comment by leifwalsh** [comment]
Can we drop a tarball on S3 and grab it in the Travis script? I don't know what you're allowed to do in Travis or how much of mesos' installation we need for tests.

**Comment by leifwalsh** [comment]
It looks like we can do pretty much whatever to install, and can just cache a directory regardless of having source?

**Comment by dgrnbrg** [comment]
Yes we can. But who would pay for that tarball?

Caching makes you pay for Travis...

**Comment by akutz** [comment]
Hi guys, FWIW, I got Mesos to build from source on Travis here https://github.com/emccode/mesos-module-dvdi/pull/13. That's the second PR - the one where I support building multiple versions of Mesos. I came across this ticket when seeing if anyone had built Mesos from source on Travis, and when I got it working, I wanted to make sure to notify y'all :)

**Comment by akutz** [comment]
One more more, @dgrnbrg mentioned caching makes you pay for Travis. I'm sure that once was the case, but Travis now supports caching for free for public projects using the container-based infrastructure.
