### ISSUE TITLE
Provide an HTTP based job tracking endpoint

### ISSUE THREAD

**Issue by tnn1t1s** [twosigma/Cook#48]
Users would like to be able to query Cook for the list of their running and waiting jobs. We've discussed this at length internally but I'd like to bring this to the open source for design, review and implementation.

**Comment by dgrnbrg** [comment]
So, I'd like to make this query one which can be answered through an external DB, like the SQLite DB I want to attach to the gRPC-based transport. I think that rich, programmatic API (as client libs) are a better bet than trying to go full HTTP REST.

**Comment by tnn1t1s** [comment]
Being able to 'curl' the status of a job, without having to find and deploy a client side library is a huge upside and will make it much easier for us to adopt this API. That said, i'm not against rich programmatic APIs that can be fronted by a simple HTTP service for a subset of operations.

**Comment by leifwalsh** [comment]
The fastest path to something people can use is to just expose a new rest endpoint that either runs the query or answers from a cache if this query is too expensive.  Keeping another DB in sync with datomic sounds like a longer project but probably one worth getting to eventually.

@tnn1t1s can you sketch out what would be a useful interface?
