### ISSUE TITLE
Unable to start server from checkout

### ISSUE THREAD

**Issue by wyegelwel** [twosigma/Cook#49]
I checked out a8e1c67c932d8e996dfaa01b58b0f2fb591907dc and tried to run lein run dev-config.edn but it failed to run because of missing dependencies. It seems tags referenced on [line 318 of components](https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/components.clj#L318) are not defined anywhere. I commented out the expression, but then I got another error about [cook.reporter on line 324](https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/components.clj#L324) and commented that expression out as well. After those changes I was able to run.

I was able to get it all running in less than 30 minutes, including pulling dependencies and debugging this. Thanks for making it easy.

**Comment by dgrnbrg** [comment]
Could you change that to (:tags riemann)?

**Comment by dgrnbrg** [comment]
Fixed in af95765
