### ISSUE TITLE
Add python client

### ISSUE THREAD

**Issue by dgrnbrg** [twosigma/Cook#5]
#4 will make this 1000x easier.

**Comment by tnn1t1s** [comment]
should that be a dependency? i'd be interested in working on this one but don't want to do throwaway code if you're planning new transport.

**Comment by dgrnbrg** [comment]
By that, I think you mean #4. I absolutely believe it should be a dependency--it will be quite easy to write the gRPC based API (should take a day or two, max), since it autogenerates half of the code we must write manually.

Before hacking on code, we should write up a design document. We can make a folder called `design_docs` with 2 subfolders, `pending` and `implemented`. That's where we can work out how these clients will work.

Some of the open questions for the python client, off the top of my head:

- All our APIs can be async, which means that while the request is in-flight, the user application could do other things. In python, should the API expose this? If so, is there an async standard we should follow? (yield, twisted, threads, something else?).
- We need to come up with a SQLlite schema for storing data. How should we store the data? Can we have turn-key SQL queries that are easy to use from Java and Python? Can we leverage the sqlite FTS5 engine to provide better search capabilities for jobs?

You can also take a stab at thinking about the gRPC schemas themselves. We'll need Job, URI, and Instance protobufs. We'll need a few rpcs: `submit` (same as POST), `delete` (same as DELETE), `query` (same as GET), and `subscribe` (like `query`, but returns a stream of instance updates, so that after the initial burst, further updates come incrementally).

The bigger question is how to prioritize the milestones: Fenzo gives us faster task scheduling and constraint-aware placement for hybrid cloud and varying machine classes. gRPC gives us a command line tool suite and simplified integration. Spark improvements will make productionalizing Spark jobs easier. They're all great, which should we do?

**Comment by leifwalsh** [comment]
Async is landing in the language in 3.5 https://www.python.org/dev/peps/pep-0492/

Right now I think the simplest way is to return a Future and yield on it to wait.  Motor (the async python driver for mongodb) does this in addition to a callback api: https://motor.readthedocs.org/en/stable/tutorial.html#using-motor-with-gen-coroutine

In my limited experience, twisted is not fun.

**Comment by tailhook** [comment]
Hm, I'm not sure, does this issue mean that `pyspark` doesn't work with Cook? Or this issue is entirely about non-spark workloads?

**Comment by dgrnbrg** [comment]
This is about non-spark workloads--specifically, a native API for
interacting with the cook preemptive scheduler from Python.

**Comment by leifwalsh** [comment]
grpc doesn't support python 3 yet, [this ticket](https://github.com/grpc/grpc/issues/282) has been open for over a year.  I'm going to take a stab at an [asyncio](https://docs.python.org/3/library/asyncio.html)/[aiohttp](http://aiohttp.readthedocs.org/en/stable/) based library targeting the existing rest api.

**Comment by DaoWen** [comment]
Cleaning up old issues. This python client is no longer on our roadmap. Closing.
