### ISSUE TITLE
lein uberjar from scheduler subdir failed

### ISSUE THREAD

**Issue by icexelloss** [twosigma/Cook#54]
ljin@hsljin:~/ws/github/Cook/scheduler$ lein uberjar
Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 5555; nested exception is: 
	java.net.BindException: Address already in use
Compilation failed: Subprocess failed

**Comment by icexelloss** [comment]
Seems to work from removing the following from jvm-opts in project.clj:

"-Dcom.sun.management.jmxremote.port=5555"
"-Dcom.sun.management.jmxremote.authenticate=false"
"-Dcom.sun.management.jmxremote.ssl=false"

**Comment by dgrnbrg** [comment]
We can add the JMX config to a different lein profile, so that it's easy to
enable JMX, but doesn't conflict by default.
