### ISSUE TITLE
Move to Metrics library in mesos/monitor.clj to standardize metrics reporting

### ISSUE THREAD

**Issue by icexelloss** [twosigma/Cook#60]
In mesos/monitor.clj, we currently report metrics on user waiting/running jobs/cpus/mem by sending riemann events directly. Instead, we should:

(1) Have a chime process query database and store the results in atoms/async-channels
(2) Have a go-loop that looks at the atoms/async-channels and register/deregister gauges.

Per discussion with @dgrnbrg

**Comment by dgrnbrg** [comment]
We should also take this opportunity to change the license here.

**Comment by DaoWen** [comment]
I believe @dposada fixed this in #710. Closing.
