### ISSUE TITLE
Document how to build cook with datomic pro

### ISSUE THREAD

**Issue by mayurjpatel** [twosigma/Cook#61]
Currently, datomic free edition jars are available in public maven repos, so lein is happy with building against it. But to use datomic pro, one has to maven install the licensed jars in local maven repo before building it. The documentation on that whole process is a little sparse. I found http://aan.io/datomic-pro-and-leiningen/ this useful after googling around.

Current documentation suggests that switching to datomic pro is as simple as s/datomic-free/datomic-pro/g project.clj.

**Comment by dgrnbrg** [comment]
Right, well clarify the docs. Previously, I assumed that you've already
used datomic, which means you ran bin/maven-install on the machine you'd
like to build cook on.

**Comment by dgrnbrg** [comment]
Hey @mayurjpatel -- sorry, I didn't mean to tell you to "well, clarify the docs"--I meant to write "we'll" (thanks mobile autocorrect :))

Thanks!

**Comment by mayurjpatel** [comment]
No worries. It's all good for the project.
