### ISSUE TITLE
Running job status not updated in mesos 0.23 and Cook

### ISSUE THREAD

**Issue by mayurjpatel** [twosigma/Cook#62]
I submitted a job via cook to a mesos 0.23 cluster. Everything seems to have worked fine, but the `instances[0].status` and `framework_id` are not getting set. On the mesos page, I do see the job as running and cook scheduler as a registered framework.

````
[
{
mem: 16,
max_retries: 3,
max_runtime: 86400000,
name: "cookjob",
command: "while [ true ]; do echo hello cook I am "$(whoami)" and MY_VAR="${MY_VAR}"; sleep 10; done",
env: {
MY_VAR: "foo1"
},
framework_id: null,
instances: [
{
start_time: 1444169356373,
task_id: "cd66e79b-9272-4d54-bbd3-e89cff8c78c0",
hostname: "some.host.domain.com",
slave_id: "20151006-201511-738201772-5050-93146-S8",
executor_id: "cd66e79b-9272-4d54-bbd3-e89cff8c78c0",
status: "unknown"
}
],
priority: 50,
status: "waiting",
uuid: "f76aa5bd-e4bb-4ef3-9ad4-5b2938efc0fd",
uris: null,
cpus: 0.5
}
]
````

**Comment by mayurjpatel** [comment]
Once I bounce the cook-scheduler process, the `framework_id` gets set for existing job and new jobs. Also, `output_url` is available in `instances` as well.
````
[
{
mem: 16,
max_retries: 3,
max_runtime: 86400000,
name: "cookjob",
command: "while [ true ]; do echo hello cook I am "$(whoami)" and MY_VAR="${MY_VAR}"; sleep 10; done",
env: {
MY_VAR: "foo2"
},
framework_id: "20150925-201810-3281262252-5050-29674-0000",
instances: [
{
start_time: 1444233400323,
output_url: "<redacted>",
task_id: "80a7cfa2-ece8-4f20-8240-7290239b5f78",
hostname: "some.host.domain.com",
slave_id: "20151006-201511-738201772-5050-93146-S6",
executor_id: "80a7cfa2-ece8-4f20-8240-7290239b5f78",
status: "unknown"
}
],
priority: 50,
status: "waiting",
uuid: "e850bb27-fd17-46b6-a7b4-f16fd0e555cb",
uris: null,
cpus: 0.5
}
]
````

**Comment by dgrnbrg** [comment]
Here's the issue: the very first time Cook is launched, it fails to populate the `framework-id` [here](https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/components.clj#L165). Unfortunately, we need to know our framework id to populate the `output_url` and the `framework_id` fields in the API.

Instead, the framework id used by `api.clj` should be late-bound by this function in the scheduler initialization: https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/mesos.clj#L87

This will ensure that the first time you start Cook on a cluster, the API works fully.

**Comment by dgrnbrg** [comment]
Was the status of the job also not being updated, besides the framework ID and the output_url?

**Comment by mayurjpatel** [comment]
Yes, status of the job was 'unknown'.

**Comment by dgrnbrg** [comment]
But the job was running on the cluster? Did restarting cook fix it?

**Comment by mayurjpatel** [comment]
Job was running. 

I just tested it now and I am seeing status propagating just fine. I did restart datomic transactor yesterday to resolve some metatransaction issue, so I think that was the culprit. Since, I cannot reproduce the bug, maybe it was something wrong with my deployment.

**Comment by dgrnbrg** [comment]
I'll chalk this up to "missing db libs". We should have a way to verify that datomic is configured correctly, though...
