### ISSUE TITLE
framework name for cookand  mesos 0.23.1 

### ISSUE THREAD

**Issue by mayurjpatel** [twosigma/Cook#63]
There is an extra dash at the end for the framework name when registered with mesos master. See screenshot below. I am not sure if it is meant to be followed by a uuid or if it is a typo.

![frameworks](https://cloud.githubusercontent.com/assets/12688620/10339641/6da806a6-6cda-11e5-865f-7068f54ba3bf.png)

**Comment by dgrnbrg** [comment]
That is a bug--it's supposed to display the git commit it was built from.
We'll fix this promptly

**Comment by dgrnbrg** [comment]
How did you launch cook? Did you use `lein run`, or did you first create a jar?

Here's the line where we construct the framework name: https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/mesos.clj#L115

Which uses this variable, which should either be the commit or `dev` if you're not running from a commit: https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/util.clj#L276-L279

The commit is injected into the jar here: https://github.com/twosigma/Cook/blob/master/scheduler/project.clj#L113-L117

**Comment by mayurjpatel** [comment]
I launched cook by running -standalone jar. I downloaded the zip file from github, rather than clone the repo and the zip file does not have .git directories. That would explain the commit not being injected in the jar. However, should cook/util check if `git-log` is empty in addition to checking for exception.

**Comment by dgrnbrg** [comment]
Yes, it should! It might even be good to throw an exception of you build
without a clone, or maybe it should say it's an "unknown" version in that
case, and print an ERROR to the log.

**Comment by leifwalsh** [comment]
When we have version numbers and publish to clojars, we'll want to inject these instead of a git hash (or in addition to one). I assume lein has a way to grab this so we can stuff it in the jar?



-- 
Cheers,
Leif

**Comment by mayurjpatel** [comment]
+1. It would be nice if `git-log` variable in `project.clj` was set to:
* version or tag of the codebase, if any
* commit hash if working from cloned directory
* "unknown" if neither of the above.

**Comment by dgrnbrg** [comment]
That is doable. We'll include this in the 1.0 release.

**Comment by dgrnbrg** [comment]
Actually, there's some kind of bug which causes lein to complain about multiple code-generated injected files. This will require more work, but will land sooner or later.
