### ISSUE TITLE
test-start-host-sandbox-syncer is flaky

### ISSUE THREAD

**Issue by pschorf** [twosigma/Cook#733]
`FAIL in (test-start-host-sandbox-syncer) (sandbox.clj:441)
expected: (= {"task.host2" "/path/to/host2/sandbox", "task.host4" "/path/to/host4/sandbox"} (clojure.core/deref task-id->sandbox-agent))
  actual: (not (= {"task.host2" "/path/to/host2/sandbox", "task.host4" "/path/to/host4/sandbox"} {"task.host4" "/path/to/host4/sandbox"}))`

**Comment by shamsimam** [comment]
Has this failed for you recently?

I tried the following in my repl:
```
(deftest test-start-host-sandbox-syncer
  (time
    (dotimes [_ 1000]
      ...)))
```
and got:
```
Running cook.test.mesos.sandbox/test-start-host-sandbox-syncer
"Elapsed time: 55040.144084 msecs"
Ran 1 test containing 16000 assertions.
No failures.
```
