### ISSUE TITLE
Spark 1.5.1

### ISSUE THREAD

**Issue by tailhook** [twosigma/Cook#75]
Hi, I'm going to try Cook for our spark installation. But we hit a bug in spark 1.5.0 which is fixed in 1.5.1.

According to the docs:
https://github.com/twosigma/Cook/tree/master/spark
.. I should use spark 1.5.0, which I can't.

So the question is, have anybody tried to use it with spark 1.5.1? (I'll probably try myself, just asking if there are known issues or patch ready to use).

**Comment by wyegelwel** [comment]
We are running 1.5.1 and the patch should apply cleanly. 

I'll make a pull request to update the docs.

Happy sparking!

**Comment by tailhook** [comment]
Thanks!
