### ISSUE TITLE
cook gpu support don't work?

### ISSUE THREAD

**Issue by dPeS** [twosigma/Cook#765]
I have mesos 1.4.0 on 1 hosts with registered 0/1 GPU in agent. Cook 1.11 is also registered but it gets no offers. Without gpu it get offers. I've tryied adding ":gpu-enabled true" to config.edn in :mesos and :scheduler sections without luck... any clues?

**Comment by dposada** [comment]
Hey @dPeS, can you explain what you mean by this:

> Without gpu it get offers

In other words, what are you changing in your environment to make Cook receive offers?

**Comment by dPeS** [comment]
all I change is: ec2 instance type - I have ansible code that provisions host is the same way

I think that:

http://mesos.apache.org/documentation/latest/gpu-support/#framework-capabilities

has sth to do with that

**Comment by dPeS** [comment]
to be precise... cook works normal (cs submit sleep 10) on m4.xlarge instance but don't work on p2.xlarge which has gpu (nvidia driver) and auto registered 1 GPU in mesos agent

**Comment by wyegelwel** [comment]
Can you provide the configuration file you started cook with?

**Comment by dPeS** [comment]
sure... 
[config.edn.txt](https://github.com/twosigma/Cook/files/1830405/config.edn.txt)
[run-local.sh.txt](https://github.com/twosigma/Cook/files/1830406/run-local.sh.txt)

+ as I said I've tryied to add ":gpu-enabled true" in different places without luck

**Comment by wyegelwel** [comment]
@dPeS Would you mind adding `:enable-gpu-support true` directly beneath `:failover-timeout-ms` and re-running? It sounds like you may have had an incorrect key name.

**Comment by dPeS** [comment]
@wyegelwel sure, will do asap and back to you, thanks for tip!

**Comment by wyegelwel** [comment]
You're welcome, good luck!

**Comment by dPeS** [comment]
@wyegelwel well I have two infos: bad and good... 

bad: placing `:enable-gpu-support true` in config didn't helped
good: with that: https://github.com/twosigma/Cook/pull/772 it works

**Comment by wyegelwel** [comment]
I'll take good and bad to only bad :)

Thanks for tracking down that bug and I'm glad it is working for you now.

**Comment by dPeS** [comment]
sure, np - thanks for great tool! cheers Daniel

**Comment by wyegelwel** [comment]
Closed with #772
