### ISSUE TITLE
Verify that Datomic has the extra jars on its classpath

### ISSUE THREAD

**Issue by dgrnbrg** [twosigma/Cook#78]
Currently, it's possible to deploy Cook and Datomic, but misconfigure Datomic, in which case jobs silently fail. This shouldn't be silent.

**Comment by DaoWen** [comment]
@pschorf - Do you know if this can still happen?

**Comment by dposada** [comment]
@pschorf ping

**Comment by pschorf** [comment]
Not sure what the original context on this was.
