### ISSUE TITLE
How to configure tasks preemption?

### ISSUE THREAD

**Issue by Orhideous** [twosigma/Cook#88]
Hello.
I was faced with some troubles when tried to set up Cook scheduler on a small cluster. 
I got successfully run Cook as Mesos framework, but I don't know how to configure tasks preemption.
Apparently, rebalancer didn't start at all, so I'd look through source code, and I had a few questions.
1. I saw references to TwoSigma servers in source code ([rebalancer.clj → get-mesos-utilization](https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/mesos/rebalancer.clj#L321)) — does that mean that rebalancer work only with them?
2. When rebalancer starts and how often does it run?
3. Is it possible to manually check DRU values for running and waiting jobs (via REST API, for example)?
4. Is it possible to configure rebalanser in the same manner as Cook — using edn-config file, not datomic?

**Comment by icexelloss** [comment]
Orhideous,

1. I have a pull request up for this: https://github.com/twosigma/Cook/pull/85
2. It is currently hardcoded (every 5 min), but we should definitely have it configurable in config.edn
3. This is not currently available
4. Currently no but we are looking into standardize rebalancer configuration as well

**Comment by dgrnbrg** [comment]
For the 4th thing, we're working on that in #12. We should have the important preemption parameters configurable by the first week of December.

**Comment by DaoWen** [comment]
The [rebalancer config options are now clearly documented](https://github.com/twosigma/Cook/blob/v1.14.1/scheduler/docs/configuration.adoc#rebalancer-configuration), and the rebalancer is tested in Travis. Closing.
