### ISSUE TITLE
Provide "simulation tests" and benchmarks

### ISSUE THREAD

**Issue by mforsyth** [twosigma/Cook#94]
# Some questions about the nature of the Cook benchmarks
## What do we want to know about how Mesos and Cook handled each job?
- Time to Start:  start_time (from Cook API response) minus internally recorded submission time
- Time to finish:  end_time (from Cook API response of a task instance in "success" state) minus internally recorded submission time
- Number of Instances?:  (in other words, the number of times each Cook task was started on a slave).  Will tell us if there is a difference in how likely the change is to preempt or runs or otherwise cause them to be interrupted
### A database of information about jobs.
- Each entry should contain the attributes from "What we want to know about how Mesos and Cook handled each job" above as well as all the contents of the JSON that was submitted AND all of the data that Cook attaches to the Task in its own database.
- This will allow us to build all sorts of reports as we go along, and even to construct ad hoc reports for a particular dataset.
- Should be portable - shouldn't have to keep Mesos cluster running in order to perform more analyisis on the data.  And even if the cluster IS left running, we need to make sure that the data doesn't change underneath our feet as we're generating different reports on it!
- We can pull everything Cook knows about each task from Cook's own Datomic database - just make a peer and load from it.
### Reports generated from the database

In general, once you've obtained the dataset of a simulation run, the idea is that it should be easy to concoct new reports to run on it.  However, we should provide some metrics "out of the box".

For each dimenssion of interest (e.g. "Time to finish"), we can output summary numbers of interest like:
- Average
- Median
- Maximum

To visualize the dimension, we could create
- historograms
- scatter plots, with x axis being something like true job calculation time?
## What will the simulation run consist of?
- A set of jobs with known qualities
  - execution time
  - number of CPU's occupied
  - memory usage
- A schedule on which those tasks are assigned
## How will we generate the task definitions for the test run?
- A way to generate a randomized set of tasks with defined constraints.
- A way to feed a predefined set of tasks (either generated randomly or hand-edited) into a simulation run

The parameters of these things need to be controllable programmatically,
so that we can easily specify the details of the workload we want to simulate,
and change it quickly.

---
# So, given all that, what are the Components of this project?
## The "consume these resources" task

This is a program, able to be placed on any Mesos slave, that should accept the following command line parameters:
- CPUs
- Memory
- running time
- exit code

Upon launch, it should immediately start to max out the suggested number of CPU's, and allocate memory to occupy the suggested amount.   It should run for the specified amount of time and exit with the specified code.
## Workload Definition File

We need a file format that defines a set of tasks that will comprise a simulation run.  It should describe the schedule on which these tasks will be submitted during the run.
## Workload Definition Generator

A process that, given a set of constraints about an intended simulation workload, generates a Workload Definition File.
## Workload Submitter

A process that, given a Workload Definition File and a Cook cluster, will submit the specified tasks to Cook on the specified schedule.

This will probably need to record some additional data somewhere, for use in analysis - just add more data to Cook's datamic perhaps (or could that possibly affect the benchmark)?
## Workload Results Accumulator

A process that, given a Workload Definition File and a Cook cluster, generates a portable Workload Results Database.
## Workload Results analysis

Processes that generate useful human readable output from a Workload Results Database.
## Hooks to run on CI?

It would be nice for CI to warn us about the impact any given change would have on the benchmarks.  It's worth exploring how realistic it is for some version of the benchmark to be run on every CI run.  There could definitely be issues here - like the tests running a long time, or using up too many resources when applied to a cluster & load that was realistic enough to matter.

**Comment by tnn1t1s** [comment]
Take a look at simulant http://www.cognitect.com/simulation-testing for
design queues and possible implementation platform.

**Comment by mforsyth** [comment]
I've been experimenting with Simulant.  So far I don't see any reason not to use it - it provides some appropriate & potentially useful conventions for tracking & running the sims.  Still leaves most of the work for us to do, but that's to be expected.

**Comment by tnn1t1s** [comment]
Right. I spent some time with the mtnygard/simulant-example repo and
thought it could easily map to what we are doing here. If we need to, we
can engage the cognitect team further.
