### ISSUE TITLE
Unable to build docker image.

### ISSUE THREAD

**Issue by PerilousApricot** [twosigma/Cook#942]
**Describe the bug**
Unable to successfully execute `scheduler/bin/build-docker-image.sh`. When doing so, I get:
```
Step 23/27 : RUN lein uberjar
 ---> Running in dd6feaf184d3
Release versions may not depend upon snapshots. 
Freeze snapshots to dated versions or set the LEIN_SNAPSHOTS_IN_RELEASE environment variable to override.
```

**To Reproduce**
1. Clone the repo and checkout `v1.19.0`
```
# HEAD detached at v1.19.0
nothing to commit, working directory clean
```
2. Execute `scheduler/bin/build-docker-image.sh`

**Expected behavior**
According to the README, this should build the binaries.

**Comment by DaoWen** [comment]
I bet we haven't run into this because no one on our team builds non-snapshot versions with that script.

The underlying problem seems to be the dependence on `[wyegelwe/mesomatic "1.0.1-r0-SNAPSHOT"]`. I'll push a non-snapshot version of mesomatic to clojars and update the dependency here.

**Comment by PerilousApricot** [comment]
Thanks! I was following the instructions in the readme and am unfamiliar
with the Clojure buildchain. I set the suggested environment variable and
it appeared to work, but it would be nice to get the readme instructions
working.

**Comment by DaoWen** [comment]
@PerilousApricot - Yes, either setting that environment variable or building a SNAPSHOT version of Cook would be a good workaround until we roll a new release with the updated dependency list.

If you have other questions about Cook, feel free to [join our Cook slack support channel](http://cookscheduler.herokuapp.com/).
